name: pathology-tutorials-complete
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Core Python
  - python=3.11
  
  # System libraries
  - openslide
  - libopencv
  - gcc_linux-64
  - gxx_linux-64
  - make
  - git
  
  # Core scientific stack
  - numpy>=1.24.0
  - pandas>=2.0.0
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - scikit-learn>=1.3.0
  - scikit-image>=0.21.0
  
  # Image processing
  - pillow>=10.0.0
  - opencv>=4.8.0
  - imageio>=2.31.0
  - tifffile>=2023.7.0
  
  # Deep learning (CPU versions)
  - pytorch>=2.0.0
  - torchvision>=0.15.0
  - cpuonly
  
  # Visualization
  - plotly>=5.15.0
  - bokeh>=3.2.0
  - ipywidgets>=8.0.0
  - tqdm>=4.65.0
  
  # Machine learning extensions
  - umap-learn>=0.5.0
  
  # Data processing
  - requests>=2.31.0
  - h5py>=3.9.0
  
  # Jupyter environment
  - jupyterlab>=4.0.0
  - ipykernel>=6.25.0
  - notebook>=7.0.0
  
  # Development tools
  - pytest>=7.4.0
  - black>=23.7.0
  
  # Additional utilities
  - click>=8.1.0
  - pyyaml>=6.0
  - joblib>=1.3.0
  
  # Pip dependencies not available in conda
  - pip
  - pip:
    - openslide-python>=1.2.0
    - timm>=0.9.0
    - transformers>=4.30.0
    - hdbscan>=0.8.29
    - optuna>=3.2.0
    - staintools>=2.1.2
    - histomicstk>=1.3.0
    - zarr>=2.16.0
    - pytest-cov>=4.1.0
    - flake8>=6.0.0
