name: pathology-tutorials
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - scikit-image
  - pillow
  - tqdm
  - requests
  - jupyterlab
  - notebook
  - ipywidgets
  - plotly
  - pytorch
  - torchvision
  - cpuonly
  - openslide
  - openslide-python
  - pip
  - pip:
    - opencv-python
